### ISSUE TITLE
Cannot resubmit a dataset in case of error during import

### ISSUE THREAD

**Issue by biorosetics** [Candihub/pixel#105]
On staging, after an attempt to upload a new file, an error is raised. There is no way to resubmit a corrected file. 

Going back to step 2 allow us to download the archive; not to submit a new file.

**Comment by jmaupetit** [comment]
I think in this case it would be nice to be able to abort a submission process and start a new one. WDYT?

**Comment by gaellelelandais** [comment]
I also think that the submission should be aborted if the files are not correct. In this situation, a statut "failed" could be writen on the history page ? (it is writen 50%)
![image](https://user-images.githubusercontent.com/20843515/34035370-21f9f7b8-e182-11e7-9430-2d2b778cd73c.png)

**Comment by jmaupetit** [comment]
Considered as fixed in #123
