### ISSUE TITLE
Add Continuous Deployment

### ISSUE THREAD

**Issue by jmaupetit** [Candihub/pixel#14]
## Purpose

We need be able to automatically deploy:

- `master` to a staging instance
- `master:tag` to a production instance

## Proposal

- Define a deployment strategy
- Use CircleCI to deploy

**Comment by pierrepo** [comment]
Please document this process. Who is deploying what, from where to where and when?

**Comment by jmaupetit** [comment]
Fixed since f7345c9 (see `docs/deployment.md`).
