### ISSUE TITLE
Consider loading entries during the deployment process

### ISSUE THREAD

**Issue by willdurand** [Candihub/pixel#145]
While deploying version 2.0.0 in production, I missed the "step" to load entries from CGD and SGD features files. I was not aware of that. I open this issue so that we'll not forget to think about it.

It might not be useful to trigger the `load_entries` command on every deployment (for example, because we need to handle potential errors caused by this step), but we have to think more about it. We could maybe create a new script on the server that the `candibot`/`pixel` user can execute (`sudo`'ed) manually.

**Comment by jmaupetit** [comment]
> We could maybe create a new script on the server that the candibot/pixel user can execute (sudo'ed) manually.

I'd 👍 this idea.

**Comment by willdurand** [comment]
I dont think it would be wise to execute this script on every deployment, loading entries takes a lot of time, and we might run into troubles like a second deployment starts before the previous one has ended.

Creating a script would still be useful.

**Comment by jmaupetit** [comment]
Yeah, you're right. Then maybe we should declare a new issue for this script?
