### ISSUE TITLE
Improve PixelSetListView layout

### ISSUE THREAD

**Issue by jmaupetit** [Candihub/pixel#153]
## Purpose

The current `PixelSetListView` tabular view does not adapt well with displayed information (_e.g._, description fields).

![screenshot-2018-1-23 pixel sets](https://user-images.githubusercontent.com/956157/35390846-0c5d6982-01dd-11e8-9108-3bf22eb4b53e.png)

## Proposal

@willdurand proposed to use an horizontal layout for each pixel set (see #148). We might consider using definition lists (`dl`).

**Comment by willdurand** [comment]
Thinking more about it, why not `overflow-x: scroll` the right panel and fix a few column widths?

**Comment by jmaupetit** [comment]
🤔 horizontal scrolling is not really user-friendly with a "simple mouse" (compared to a trackpad or a magic mouse :trollface:), but that's an interesting alternative.

**Comment by willdurand** [comment]
I guess on reasonable screens, scrolling would not even appear. Right about the trackpad/magic mouse..

**Comment by willdurand** [comment]
I tried a new layout in #156. Let's see how it works.
