### ISSUE TITLE
Add title on submission status icons to help understand their meaning

### ISSUE THREAD

**Issue by willdurand** [Candihub/pixel#167]

**Comment by willdurand** [comment]
@jmaupetit could you please describe the different icons and their meanings? I am very confused and I'd like to fix this. I think it is important for external users (like me).

**Comment by jmaupetit** [comment]
* check mark: submission done with success
* exclamation triangle: submission failed
* pause: submission in progress

**Comment by willdurand** [comment]
> pause: submission in progress

Can we use this icon: http://fontawesome.io/icon/spinner/?
