### ISSUE TITLE
Fix random test suite failure

### ISSUE THREAD

**Issue by jmaupetit** [Candihub/pixel#195]
## Purpose

The following test randomly fails:

`apps/explorer/tests/test_views.py::PixelSetListViewTestCase::test_search_filter_with_keywords`

## Proposal

I think it might be related to experiment random selection in the `make_development_fixtures` utility. See:
https://github.com/Candihub/pixel/blob/master/apps/core/management/commands/make_development_fixtures.py#L40

**Comment by willdurand** [comment]
ah good catch, maybe some experiments are not always chosen because of the randomness or same experiments get assigned twice..

Should we get rid of the random call?

**Comment by jmaupetit** [comment]
I think yes. It would be more predictable to iterate over experiments.

**Comment by willdurand** [comment]
Re-opening because the patch did not fix it..
