### ISSUE TITLE
Add new "explore" view for multi-pixel sets exploration

### ISSUE THREAD

**Issue by willdurand** [Candihub/pixel#229]
The page should be similar to the pixel set detail view but will be accessed from the pixel sets list view, based on the pixel sets selected (session). Subset selection should be possible as well as export and preview.

Should we display information about the selected pixel sets? (current top left panel on the detail view). Maybe the list of the selected pixel sets with a link to their detail view would be enough.

**Comment by gaellelelandais** [comment]
I also think that a list or the pixel sets with a link to their detail view is enough.

**Comment by willdurand** [comment]
So this page is not really "similar to the pixel set detail view". I have started to update the page and the features in #240.

The table with the pixels at the bottom should be a view similar to the CSV file exported in the "Pixel Set list view".

**Comment by gaellelelandais** [comment]
Yes. I was not clear enough. Sorry. The table that is represented at the bottom of the page should organize like the table we can export in CSV, when several pixel sets are selected.

**Comment by willdurand** [comment]
Perfect, it is slightly more work but that should be ok.

I am a little concerned with the performance cost though, because displaying all the pixels of all the selected pixel sets might be too much. That's why we limit the table in the pixel set detail view. I haven't looked at how to do this new table yet though, so I might find a way to limit the information displayed.

**Comment by willdurand** [comment]
I have two questions related to the export feature:

- when no subset has been defined (so we have all the pixels from all the pixel sets), the export button should send the CSV file like on the list view? (when one clicks on the "export" button on the left)

- what do we want when a subset of pixels ha been defined? the same CSV with only the pixels selected? Or only the list of pixels like on the detail view of a pixel set?

**Comment by gaellelelandais** [comment]
Yes, when no subset has been defined, the export button should send the CSV file, like the one available on the list view.
When a subset of pixels (based on OmicsUnits names) has been defined, the exported file should be the same CSV file (same columns), but with only the OmicsUnit selected (this file will have less lines that the previous one). Ok ?
