### ISSUE TITLE
Python version of dev. env. conflicts with system version (3.6 -> 3.5)

### ISSUE THREAD

**Issue by biorosetics** [Candihub/pixel#24]
Development environment requires `Python 3.6`. Right now, Ubuntu 16.04 (16.04.3 LTS / xenial) comes with both Python 2.7 and Python 3.5 by default. Do you require some specific function of Python3.6 for the deployment ? Could we keep the system version or should I install tha latest version ?

**Comment by pierrepo** [comment]
I agree. Downgrading Python requirement to Python 3.5 could be good.

**Comment by jmaupetit** [comment]
Are we talking about a VMs to run staging and production instances of pixel? Because we will deploy via a CircleCI container.

Python 3.5 will be sufficient enough until we will need a better `asyncio` or typing support 😉

**Comment by biorosetics** [comment]
Following discussion with @jmaupetit, will deploy with a docker image that have an independant python version.
