### ISSUE TITLE
Dev fixtures do not populate cached fields

### ISSUE THREAD

**Issue by willdurand** [Candihub/pixel#242]
When inserting `dev` fixtures with `make boostrap`, the `cached_*` fields are
not updated. This is weird because all tests pass and submissions behave
correctly. Using admin action "update cached fields" fixes the problem.

/cc @jmaupetit

**Comment by jmaupetit** [comment]
Fixtures are hard-coded and do not contain cached data. You need to update them manually. See for example: https://github.com/Candihub/pixel/blob/master/apps/core/fixtures/initial_data.json
