### ISSUE TITLE
Add documentation regarding the repository to be created before data importation

### ISSUE THREAD

**Issue by gaellelelandais** [Candihub/pixel#249]
To properly import a new datasets the following repository have to be created in the database :
- PARTNERS
- PUBMED
They are associated to the statut Unpublished / Published of the Pixel Sets taht are imported in the system.

**Comment by willdurand** [comment]
Maybe we should create these two entries by default, like with fixtures or `init` data. I dont know how it works in Django, but there must be something. cc @jmaupetit

**Comment by willdurand** [comment]
Thanks. So it seems we have it already, but they weren't loaded automatically. Can we `loaddata` as many times as we want?

**Comment by willdurand** [comment]
Also, it is documented already 😅 https://github.com/Candihub/pixel/blob/master/docs/management_commands.md#initial-data
