### ISSUE TITLE
Archive source code to Zenodo

### ISSUE THREAD

**Issue by pierrepo** [Candihub/pixel#289]
3 steps:

- [x] collect [ORCIDs](https://orcid.org/) from authors
- [x] write config file for automatic import to [Zenodo](https://zenodo.org/)
- [x] connect GitHub to Zenodo
     Useful docs: 
    + [Making Your Code Citable](https://guides.github.com/activities/citable-code/)
    + [Requesting organization approval for an OAuth App you've already authorized for your personal account](https://help.github.com/articles/requesting-organization-approval-for-oauth-apps/)

**Comment by jmaupetit** [comment]
Hi there 👋 my ORCID is: https://orcid.org/0000-0001-6285-6646

**Comment by willdurand** [comment]
https://orcid.org/0000-0001-6925-8200

I think we need to add a JSON file for zenodo too, last time I used the automatic import, things were not properly configured.

**Comment by willdurand** [comment]
ah well it is written in the issue description.. nevermind.

**Comment by gaellelelandais** [comment]
Hi @pierrepo , 
My ORCID : https://orcid.org/0000-0002-2842-6172

**Comment by thomasdenecker** [comment]
Hi @pierrepo ,
My ORCID is https://orcid.org/0000-0003-1421-7641

**Comment by biorosetics** [comment]
Hello @pierrepo, https://orcid.org/0000-0003-1271-795X
