### ISSUE TITLE
Could the use of bumpversion ease the release proces?

### ISSUE THREAD

**Issue by pierrepo** [Candihub/pixel#290]
[Bumpversion](https://github.com/peritus/bumpversion) is a small utility that increment version number in many files simultaneously.

Its configuration and use is straightforward. See for instance: 
- [config file](https://github.com/pierrepo/PBxplore/blob/master/devtools/bumpversion.cfg)
- [use](https://github.com/pierrepo/PBxplore/blob/master/devtools/RELEASE.md#update-version-number)

**Comment by jmaupetit** [comment]
I've never used it, but I think it could be a good tool to automate boring parts of the release process.

**Comment by pierrepo** [comment]
yes, especially useful to avoid forgetting file you have to update the version number ;-)
