### ISSUE TITLE
Bug report : Pixel duplication problem

### ISSUE THREAD

**Issue by gaellelelandais** [Candihub/pixel#292]
When the database comprises two different type of Omics Unit Types (for instance here "protein" and "mRNA"), new import of Pixel Sets results in Pixel duplication. Each Omics Unit seems to be associated to all Omics Unit Types declared in the database (see pictures below for an illustration).

![image](https://user-images.githubusercontent.com/20843515/43311830-cab52a6c-918b-11e8-8632-e3b73fb28ecc.png)
![image](https://user-images.githubusercontent.com/20843515/43311841-d558d27a-918b-11e8-832f-2a13830fbf2a.png)
![image](https://user-images.githubusercontent.com/20843515/43311855-e9b1506c-918b-11e8-8605-30af5aef6cea.png)

**Comment by willdurand** [comment]
File: [meta.xlsx.txt](https://github.com/Candihub/pixel/files/2239194/meta.xlsx.txt)

**Comment by willdurand** [comment]
@jmaupetit not sure but there is this for-loop here: https://github.com/Candihub/pixel/commit/0b18445f#diff-e9157813b7e0eafa4e55bb1ad7c66484R149

That might be the problem, no? I am not sure to understand what's happening to be honest.

@gaellelelandais can we have the full archive or a smaller one that reproduces the issue? the `meta.xlsx` is not enough.

**Comment by gaellelelandais** [comment]
@willdurand : you can find all the data files here : https://pixel.candihub.eu/submission/12/
I also attach the full archive below :
[dataset_1.zip](https://github.com/Candihub/pixel/files/2269901/dataset_1.zip)

**Comment by jmaupetit** [comment]
I have the feeling that this bug is related to the recent upgrade of `openpyxl` (XLSX files parser). After upgrading dependencies (see #294), I wasn't able to reproduce this bug locally. I'll make a new release (`4.0.1`) that we can deploy and test in staging.

**Comment by gaellelelandais** [comment]
Juste to be sure we are working on a promising solution,  you confirm Julien that you were able to reproduce the bug locally before the upgrade ? 

-- 
------------------------------------------------------
Gaëlle LELANDAIS
Pr. Université Paris-Sud
Institut de Biologie Intégrative de la Cellule, campus Orsay
Tel : 01.69.82.62.26
 
Notez que les messages que je pourrais envoyer en dehors des heures de travail ne requièrent ni réponse immédiate ni réponse en dehors des heures de travail.
------------------------------------------------------
