### ISSUE TITLE
Problem with the graphical display of "Pixels by Omics Area" 

### ISSUE THREAD

**Issue by gaellelelandais** [Candihub/pixel#293]
See the figure below (an error message is written "Table has no columns") :
![image](https://user-images.githubusercontent.com/20843515/43376020-cc1bbe8c-93b8-11e8-9753-e49d05bd9751.png)

**Comment by gaellelelandais** [comment]
@jmaupetit or @willdurand , can you tell me if this bug is hard to fix ? Thx

**Comment by willdurand** [comment]
I cannot reproduce with the development fixtures (i.e. by installing Pixel locally). On which environment do you see this? Also, how many omics areas do you expect?

With only one omics area (development fixtures), we get a graph. This warning means the SQL query has returned 0 results.

**Comment by gaellelelandais** [comment]
I see this on the Pixel instance which is on our server candihub : https://pixel.candihub.eu/
I also have the feeling that this is coming from the SQL query, which (maybe) does not take into the hierarchy for omics area (see the graph organisation of omics area - we can discuss that on slack for more details).
