### ISSUE TITLE
Need more doc regarding basic installation and setup

### ISSUE THREAD

**Issue by pierrepo** [Candihub/pixel#54]
`docker` dans `docker-compose` are listed as requirements but a small installation notice should be provided. As simple as, for Debian / Ubuntu systems:

```
apt-get install docker docker-compose
```

**Comment by pierrepo** [comment]
I disagree. `docker` and `docker-compose` are essential dependencies for this project. Users need to have information on how to install them properly.
However, there is no need to copy/paste installation procedure from elsewhere. A link will be enough.
So, could you add in the `README.md` file:
- [ ] the minimal required version for `docker-compose`
- [ ] a small note before the *Quick start* telling how to install`docker` and `docker-compose`, with links to correct documentation, as you did in your previous answer.

I think that should solve this issue.

**Comment by jmaupetit** [comment]
It seems fair to me. This is not what I understand from your first message.

**Comment by pierrepo** [comment]
In my first message, I had no instruction on how to install properly `docker` and `docker-compose`. So I tried the basic installation tool provided by Ubuntu.
This lead to issue #55 . That's why we need clear resources on how to install essential requirements.
